### ISSUE TITLE
website hacked - please fix

### ISSUE THREAD

**Issue by computersalat** [ipfs/ipfs-website#149]
getting Mails with this link URL:

https://ipfs.io/ipfs/bafkreibd6edcrojqovd4ic7g47fcgqex4uaxgnvskbh4yojoudi5pph35m?filename=index(2).html#chris@computersalat.de

**Comment by Stebalien** [comment]
ipfs.io is a public gateway to the IPFS network. Please report abuse to abuse@ipfs.io.

**Comment by computersalat** [comment]
@Stebalien 
sorry for disturbance
