### ISSUE TITLE
v3 missing Brave in Browsers section

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-website#281]
"Browsers" section at the bottom of https://ipfs.tech/developers/ suggestions:

**(1)** Opera and Brave have native support and not extension so maybe replace "extensions" with "web browser solutions" ?

**(2)**  is missing Brave:

>  ![2023-09-06_22-44](https://github.com/ipfs/ipfs-website/assets/157609/25a4b03a-4ae0-4753-8a78-697140b2543b)

I think an easy fix is to do what we already do for Opera, and link to relevant blogpost (https://brave.com/ipfs-support/).
Brave logo asset is  at https://brave.com/brave-branding-assets/

 **(3)** Browsers  and extensions are more user-facing, and not Developer tools. Could we move "Browsers" section from https://ipfs.tech/developers/ to https://ipfs.tech/ right under "Get Started"  section? It is probably the most useful info for regular users who want to browse websites hosted on IPFS, and we bury it under "Developers" for some reason. 

cc @cwaring  thoughts?

**Comment by cwaring** [comment]
Thanks for catching that, I've added Brave [back](#282) and tweaked the copy a little. I agree we should review the position of this in a future update, perhaps another CTA from the homepage to this section will be suitable in the meantime?
