### ISSUE TITLE
Mobile version fails to load in Firefox on Android 

### ISSUE THREAD

**Issue by lidel** [ipfs/ipfs-website#287]
Unsure if real bug or a a cache hiccup (unable to reproduce in Chrome, only Firefox)
Is anyone else able to reproduce below with https://play.google.com/store/apps/details?id=org.mozilla.firefox&hl=en&gl=US ?

![Screenshot_20230913-001826.png](https://github.com/ipfs/ipfs-website/assets/157609/d4f1d456-238c-4e80-8ec9-dde3a8b5ac07)

**Comment by cwaring** [comment]
Does it load correctly in a new private tab? Possible this is cache related if so.

**Comment by cwaring** [comment]
Tested via browserstack and unable to reproduce, possible this was related to caching but we can continue to monitor.

<img width="474" alt="2023-09-13 @ 10 42 36@2x" src="https://github.com/ipfs/ipfs-website/assets/106938/7c9cd438-cc31-4eec-8a5d-c1e92a780eda">

<img width="451" alt="2023-09-13 @ 10 41 48@2x" src="https://github.com/ipfs/ipfs-website/assets/106938/dca2b52b-ec23-4c7f-bfd9-5cbcba107ba4">

<img width="311" alt="2023-09-13 @ 10 43 48@2x" src="https://github.com/ipfs/ipfs-website/assets/106938/15a6b2a8-e155-4a44-bf1b-c037c7161ee0">
